# Generated by Django 4.2.16 on 2024-11-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='news_images/')),
                ('category', models.CharField(choices=[('featured', 'Featured'), ('popular', 'Popular'), ('latest', 'Latest'), ('most_viewed', 'Most Viewed'), ('most_read', 'Most Read'), ('most_recent', 'Most Recent')], max_length=20)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
