# Generated by Django 4.2.16 on 2024-11-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_news_filter_alter_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('featured', 'Featured'), ('popular', 'Popular'), ('latest', 'Latest'), ('technology', 'Technology'), ('sports', 'Sports'), ('nieee', 'Nieee'), ('college', 'College')], max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='filter',
            field=models.CharField(blank=True, choices=[('most_viewed', 'Most Viewed'), ('most_read', 'Most Read'), ('most_recent', 'Most Recent')], max_length=50, null=True),
        ),
    ]
